apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-postfix-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  config: |
    hostname: {{ .Values.hostname }}
    heloWhitelist: {{ .Values.postfix.heloWhitelist }}
    postscreenAccessList: {{ .Values.postfix.postscreenAccessList }}
    ptrWhitelist: {{ .Values.postfix.ptrWhitelist }}
