apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-postfix-templates
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  # /etc/postfix/
  master.cf.j2: |
    #
    # Postfix master process configuration file.  For details on the format
    # of the file, see the master(5) manual page (command: "man 5 master" or
    # on-line: http://www.postfix.org/master.5.html).
    #
    # Do not forget to execute "postfix reload" after editing this file.
    #
    # ==========================================================================
    # service type  private unpriv  chroot  wakeup  maxproc command + args
    #               (yes)   (yes)   (no)    (never) (100)
    # ==========================================================================
    #smtp      inet  n       -       n       -       -       smtpd
    smtp       inet  n       -       n       -       1       postscreen
        -o smtpd_sasl_auth_enable=no
    # Additional listener for proxy protocol
    26         inet  n       -       n       -       1       postscreen
        -o postscreen_upstream_proxy_protocol=haproxy
        -o smtpd_sasl_auth_enable=no
    smtpd      pass  -       -       n       -       -       smtpd
    dnsblog    unix  -       -       n       -       0       dnsblog
    tlsproxy   unix  -       -       n       -       0       tlsproxy
    submission inet  n       -       n       -       -       smtpd
        -o syslog_name=postfix/submission
        -o smtpd_tls_security_level=may
        -o smtpd_sasl_auth_enable=yes
        -o smtpd_sasl_type=dovecot
        -o smtpd_sasl_path=inet:tachydromos-dovecot:3659
        -o smtpd_sasl_security_options=noanonymous
        -o smtpd_tls_auth_only=no
        -o smtpd_reject_unlisted_recipient=no
        -o smtpd_client_restrictions=$mua_client_restrictions
        -o smtpd_helo_restrictions=
        -o smtpd_helo_required=no
        -o smtpd_sender_restrictions=$mua_sender_restrictions
        -o smtpd_sender_login_maps=ldap:/etc/postfix/ldap/sender-login-maps.cf
        -o smtpd_recipient_restrictions=
        -o smtpd_relay_restrictions=$mua_relay_restrictions
        -o milter_macro_daemon_name=ORIGINATING
        -o cleanup_service_name=submission-header-cleanup
        -o smtpd_tls_cert_file=/tls/tls.crt
        -o smtpd_tls_key_file=/tls/tls.key
    smtps     inet  n       -       n       -       -       smtpd
        -o syslog_name=postfix/smtps
        -o smtpd_tls_wrappermode=yes
        -o smtpd_sasl_auth_enable=yes
        -o smtpd_sasl_type=dovecot
        -o smtpd_sasl_path=inet:tachydromos-dovecot:3659
        -o smtpd_sasl_security_options=noanonymous
        -o smtpd_tls_auth_only=yes
        -o smtpd_reject_unlisted_recipient=no
        -o smtpd_client_restrictions=$mua_client_restrictions
        -o smtpd_helo_restrictions=
        -o smtpd_helo_required=no
        -o smtpd_sender_restrictions=$mua_sender_restrictions
        -o smtpd_sender_login_maps=ldap:/etc/postfix/ldap/sender-login-maps.cf
        -o smtpd_recipient_restrictions=
        -o smtpd_relay_restrictions=$mua_relay_restrictions
        -o milter_macro_daemon_name=ORIGINATING
        -o cleanup_service_name=submission-header-cleanup
        -o smtpd_tls_cert_file=/tls/tls.crt
        -o smtpd_tls_key_file=/tls/tls.key
    #628       inet  n       -       n       -       -       qmqpd
    pickup    unix  n       -       n       60      1       pickup
    cleanup   unix  n       -       n       -       0       cleanup
    qmgr      unix  n       -       n       300     1       qmgr
    #qmgr     unix  n       -       n       300     1       oqmgr
    tlsmgr    unix  -       -       n       1000?   1       tlsmgr
    rewrite   unix  -       -       n       -       -       trivial-rewrite
    bounce    unix  -       -       n       -       0       bounce
    defer     unix  -       -       n       -       0       bounce
    trace     unix  -       -       n       -       0       bounce
    verify    unix  -       -       n       -       1       verify
    flush     unix  n       -       n       1000?   0       flush
    proxymap  unix  -       -       n       -       -       proxymap
    proxywrite unix -       -       n       -       1       proxymap
    smtp      unix  -       -       n       -       -       smtp
    relay     unix  -       -       n       -       -       smtp
        -o syslog_name=postfix/$service_name
    #       -o smtp_helo_timeout=5 -o smtp_connect_timeout=5
    showq     unix  n       -       n       -       -       showq
    error     unix  -       -       n       -       -       error
    retry     unix  -       -       n       -       -       error
    discard   unix  -       -       n       -       -       discard
    local     unix  -       n       n       -       -       local
    virtual   unix  -       n       n       -       -       virtual
    lmtp      unix  -       -       n       -       -       lmtp
    anvil     unix  -       -       n       -       1       anvil
    scache    unix  -       -       n       -       1       scache
    postlog   unix-dgram n  -       n       -       1       postlogd
    # Improve privacy by removing headers
    submission-header-cleanup unix n - n    -       0       cleanup
        -o header_checks=regexp:/etc/postfix/submission_header_cleanup
    #
    # ====================================================================
    # Interfaces to non-Postfix software. Be sure to examine the manual
    # pages of the non-Postfix software to find out what options it wants.
    #
    # Many of the following services use the Postfix pipe(8) delivery
    # agent.  See the pipe(8) man page for information about ${recipient}
    # and other message envelope options.
    # ====================================================================
    #
    # maildrop. See the Postfix MAILDROP_README file for details.
    # Also specify in main.cf: maildrop_destination_recipient_limit=1
    #
    #maildrop  unix  -       n       n       -       -       pipe
    #  flags=DRhu user=vmail argv=/usr/local/bin/maildrop -d ${recipient}
    #
    # ====================================================================
    #
    # Recent Cyrus versions can use the existing "lmtp" master.cf entry.
    #
    # Specify in cyrus.conf:
    #   lmtp    cmd="lmtpd -a" listen="localhost:lmtp" proto=tcp4
    #
    # Specify in main.cf one or more of the following:
    #  mailbox_transport = lmtp:inet:localhost
    #  virtual_transport = lmtp:inet:localhost
    #
    # ====================================================================
    #
    # Cyrus 2.1.5 (Amos Gouaux)
    # Also specify in main.cf: cyrus_destination_recipient_limit=1
    #
    #cyrus     unix  -       n       n       -       -       pipe
    #  user=cyrus argv=/cyrus/bin/deliver -e -r ${sender} -m ${extension} ${user}
    #
    # ====================================================================
    #
    # Old example of delivery via Cyrus.
    #
    #old-cyrus unix  -       n       n       -       -       pipe
    #  flags=R user=cyrus argv=/cyrus/bin/deliver -e -m ${extension} ${user}
    #
    # ====================================================================
    #
    # See the Postfix UUCP_README file for configuration details.
    #
    #uucp      unix  -       n       n       -       -       pipe
    #  flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)
    #
    # ====================================================================
    #
    # Other external delivery methods.
    #
    #ifmail    unix  -       n       n       -       -       pipe
    #  flags=F user=ftn argv=/usr/lib/ifmail/ifmail -r $nexthop ($recipient)
    #
    #bsmtp     unix  -       n       n       -       -       pipe
    #  flags=Fq. user=bsmtp argv=/usr/local/sbin/bsmtp -f $sender $nexthop $recipient
    #
    #scalemail-backend unix -       n       n       -       2       pipe
    #  flags=R user=scalemail argv=/usr/lib/scalemail/bin/scalemail-store
    #  ${nexthop} ${user} ${extension}
    #
    #mailman   unix  -       n       n       -       -       pipe
    #  flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py
    #  ${nexthop} ${user}
  main.cf.j2: |
    # Network
    mynetworks      = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
    inet_interfaces = all
    inet_protocols  = ipv4
    myhostname      = {{ `{{ hostname }}` }}
    mydestination   = $myhostname, localhost

    # Mail queue
    maximal_queue_lifetime = 1h
    bounce_queue_lifetime  = 1h
    maximal_backoff_time   = 15m
    minimal_backoff_time   = 5m
    queue_run_delay        = 5m

    # TLS - General
    tls_ssl_options     = NO_COMPRESSION
    tls_high_cipherlist = EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH:CAMELLIA128-SHA:AES128-SHA

    # TLS - Outgoing mails
    smtp_tls_security_level         = dane
    smtp_dns_support_level          = dnssec
    smtp_tls_session_cache_database = lmdb:${data_directory}/smtp_scache
    smtp_tls_protocols              = !SSLv2, !SSLv3
    smtp_tls_ciphers                = high
    smtp_tls_CAfile                 = /etc/ssl/certs/ca-certificates.crt

    # TLS - Incoming mails
    smtpd_tls_security_level         = may
    smtpd_tls_protocols              = !SSLv2, !SSLv3
    smtpd_tls_ciphers                = high
    smtpd_tls_session_cache_database = lmdb:${data_directory}/smtpd_scache
    smtpd_tls_cert_file              = /tls/tls.crt
    smtpd_tls_key_file               = /tls/tls.key

    # Local transport to mailbox
    virtual_transport = lmtp:tachydromos-dovecot:24

    # Milter
    smtpd_milters         = inet:tachydromos-rspamd:11332
    non_smtpd_milters     = inet:tachydromos-rspamd:11332
    milter_protocol       = 6
    milter_mail_macros    = i {mail_addr} {client_addr} {client_name} {auth_authen}
    milter_default_action = accept

    # Relay restrictions
    smtpd_relay_restrictions = reject_non_fqdn_recipient
                               reject_unknown_recipient_domain
                               permit_mynetworks
                               reject_unauth_destination

    # Receiving restrictions
    smtpd_recipient_restrictions = check_recipient_access ldap:/etc/postfix/ldap/recipient-access.cf

    # Sending restrictions
    smtpd_client_restrictions = permit_mynetworks
                                check_client_access lmdb:/etc/postfix/without_ptr
                                reject_unknown_client_hostname

    # Connection restrictions
    smtpd_helo_required     = yes
    smtpd_helo_restrictions = permit_mynetworks
                              check_helo_access lmdb:/etc/postfix/helo_access
                              reject_invalid_helo_hostname
                              reject_non_fqdn_helo_hostname
                              reject_unknown_helo_hostname
    smtpd_data_restrictions = reject_unauth_pipelining

    # Client restrictions
    mua_relay_restrictions  = reject_non_fqdn_recipient
                              reject_unknown_recipient_domain
                              permit_mynetworks
                              permit_sasl_authenticated
                              reject
    mua_sender_restrictions = permit_mynetworks
                              reject_non_fqdn_sender
                              reject_sender_login_mismatch
                              permit_sasl_authenticated
                              reject
    mua_client_restrictions = permit_mynetworks
                              permit_sasl_authenticated
                              reject

    # Whitelist / Blocklist
    postscreen_access_list      = permit_mynetworks
                                  lmdb:/etc/postfix/postscreen_access
    postscreen_blacklist_action = drop
    postscreen_greet_action     = drop
    postscreen_dnsbl_threshold  = 2
    postscreen_dnsbl_sites      = ix.dnsbl.manitu.net*2
                                  zen.spamhaus.org*2
    postscreen_dnsbl_action     = drop

    # LDAP lookups
    virtual_alias_maps      = ldap:/etc/postfix/ldap/aliases.cf
    virtual_mailbox_maps    = ldap:/etc/postfix/ldap/accounts.cf
    virtual_mailbox_domains = ldap:/etc/postfix/ldap/domains.cf
    local_recipient_maps    = $virtual_mailbox_maps

    # Misc
    mailbox_size_limit  = 0
    message_size_limit  = 52428800
    biff                = no
    append_dot_mydomain = no
    recipient_delimiter = +
    lmtp_host_lookup    = native
    smtp_host_lookup    = native
    compatibility_level = 2
    maillog_file        = /dev/stdout
  helo_access.j2: |
    {{ `{{ heloWhitelist }}` }}
  postscreen_access.j2: |
    {{ `{{ postscreenAccessList }}` }}
  without_ptr.j2: |
    {{ `{{ ptrWhitelist }}` }}
  submission_header_cleanup.j2: |
    /^Received:/ IGNORE
    /^X-Originating-IP:/ IGNORE
    /^X-Mailer:/ IGNORE
    /^User-Agent:/ IGNORE
  # /etc/postfix/ldap/
  accounts.cf.j2: |
    server_host = {{ `{{ ldapHost }}` }}
    server_port = {{ `{{ ldapPort }}` }}
    bind        = yes
    bind_dn     = {{ `{{ ldapBinddnAttributeType }}` }}={{ `{{ ldapBinddnUsername }}` }},{{ `{{ ldapRootDn }}` }}
    bind_pw     = {{ `{{ ldapBinddnPassword }}` }}
    search_base = {{ `{{ ldapUserSearchBase }}` }},{{ `{{ ldapRootDn }}` }}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = (&(objectClass=mailAccount)(mailActive=TRUE)(mail=%s))
    result_attribute = mail
  aliases.cf.j2: |
    server_host = {{ `{{ ldapHost }}` }}
    server_port = {{ `{{ ldapPort }}` }}
    bind        = yes
    bind_dn     = {{ `{{ ldapBinddnAttributeType }}` }}={{ `{{ ldapBinddnUsername }}` }},{{ `{{ ldapRootDn }}` }}
    bind_pw     = {{ `{{ ldapBinddnPassword }}` }}
    search_base = {{ `{{ ldapUserSearchBase }}` }},{{ `{{ ldapRootDn }}` }}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = (&(objectClass=mailAccount)(mailActive=TRUE)(mailAlias=%s))
    result_attribute = mail
  domains.cf.j2: |
    server_host = {{ `{{ ldapHost }}` }}
    server_port = {{ `{{ ldapPort }}` }}
    bind        = yes
    bind_dn     = {{ `{{ ldapBinddnAttributeType }}` }}={{ `{{ ldapBinddnUsername }}` }},{{ `{{ ldapRootDn }}` }}
    bind_pw     = {{ `{{ ldapBinddnPassword }}` }}
    search_base = {{ `{{ ldapDomainSearchBase }}` }},{{ `{{ ldapRootDn }}` }}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = (&(objectClass=organizationalUnit)(ou=%s))
    result_attribute = ou
  recipient-access.cf.j2: |
    server_host = {{ `{{ ldapHost }}` }}
    server_port = {{ `{{ ldapPort }}` }}
    bind        = yes
    bind_dn     = {{ `{{ ldapBinddnAttributeType }}` }}={{ `{{ ldapBinddnUsername }}` }},{{ `{{ ldapRootDn }}` }}
    bind_pw     = {{ `{{ ldapBinddnPassword }}` }}
    search_base = {{ `{{ ldapUserSearchBase }}` }},{{ `{{ ldapRootDn }}` }}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = (&(objectClass=mailAccount)(mail=%s)(|(mailSendOnly=TRUE)(mailActive=FALSE)))
    result_attribute = mail
    result_format    = REJECT
  sender-login-maps.cf.j2: |
    server_host = {{ `{{ ldapHost }}` }}
    server_port = {{ `{{ ldapPort }}` }}
    bind        = yes
    bind_dn     = {{ `{{ ldapBinddnAttributeType }}` }}={{ `{{ ldapBinddnUsername }}` }},{{ `{{ ldapRootDn }}` }}
    bind_pw     = {{ `{{ ldapBinddnPassword }}` }}
    search_base = {{ `{{ ldapUserSearchBase }}` }},{{ `{{ ldapRootDn }}` }}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = (&(objectClass=mailAccount)(mailActive=TRUE)(|(mail=%s)(mailAlias=%s)(mailSuperUser=TRUE)))
    result_attribute = mail
