apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-postfix-entrypoint
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  entrypoint.py: |
    #!/usr/bin/python3
    import logging
    import os
    import shutil
    import subprocess
    import yaml

    import jinja2 as j2


    class LogFormatter(logging.Formatter):
      blue = '\x1b[34m'
      green = '\x1b[32m'
      yellow = '\x1b[33m'
      red = '\x1b[31m'
      bold_red = '\x1b[31;1m'
      purple = '\x1b[35m'
      reset = '\x1b[0m'
      time = purple + '%(asctime)s '
      message = reset + '==> %(message)s'

      def __init__(self):
        super().__init__()
        self.FORMATS = {
          logging.DEBUG: self.time + self.blue + '%(levelname)s ' + self.message,
          logging.INFO: self.time + self.green + '%(levelname)s ' + self.message,
          logging.WARNING: self.time + self.yellow + '%(levelname)s ' + self.message,
          logging.ERROR: self.time + self.red + '%(levelname)s ' + self.message,
          logging.CRITICAL: self.time + self.bold_red + '%(levelname)s ' + self.message,
        }

      def format(self, record):
        log_fmt = self.FORMATS.get(record.levelno)
        formatter = logging.Formatter(log_fmt)
        return formatter.format(record)

    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)
    loghandler = logging.StreamHandler()
    loghandler.setLevel(logging.DEBUG)
    loghandler.setFormatter(LogFormatter())
    logger.addHandler(loghandler)


    def load_config():
      config = {}
      with open('/mnt/config', 'r') as filestream:
        config.update(yaml.safe_load(filestream))
      with open('/mnt/ldap-config', 'r') as filestream:
        config.update(yaml.safe_load(filestream))
      with open('/mnt/ldap-secrets', 'r') as filestream:
        config.update(yaml.safe_load(filestream))
      return config


    def generate_config(template, targetDir, owner='root', group='root', mode=0o644, dirmode=0o755):
      target = targetDir + template.removesuffix('.j2')
      logger.info(f'Generating config {target}')
      configfile = j2Env.get_template(template).render(config)
      with open(target, 'w') as fileHandler:
        fileHandler.write(configfile)
      set_permissions(target, False, owner, group, mode, dirmode)


    def set_permissions(target, recursive, owner='root', group='root', mode=0o644, dirmode=0o755):
      if recursive:
        for dirpath, dirnames, filenames in os.walk(target):
          shutil.chown(dirpath, owner, group)
          os.chmod(dirpath, dirmode)
          for filename in filenames:
            shutil.chown(os.path.join(dirpath, filename), owner, group)
            os.chmod(os.path.join(dirpath, filename), mode)
      else:
        shutil.chown(target, owner, group)
        if os.path.isdir(target):
          os.chmod(target, dirmode)
        else:
          os.chmod(target, mode)


    def j2Finalize(value):
      return value if value is not None else ''


    config = load_config()
    j2Env = j2.Environment(loader=j2.FileSystemLoader('/mnt/templates'), finalize=j2Finalize, keep_trailing_newline=True)


    configDir = '/etc/postfix/'
    ldapDir = configDir + 'ldap/'
    if not os.path.isdir(ldapDir):
      os.mkdir(ldapDir)
      set_permissions(ldapDir, False)


    generate_config('main.cf.j2', configDir)
    generate_config('master.cf.j2', configDir)
    generate_config('submission_header_cleanup.j2', configDir)
    generate_config('postscreen_access.j2', configDir)
    generate_config('helo_access.j2', configDir)
    generate_config('without_ptr.j2', configDir)

    generate_config('accounts.cf.j2', ldapDir)
    generate_config('aliases.cf.j2', ldapDir)
    generate_config('domains.cf.j2', ldapDir)
    generate_config('recipient-access.cf.j2', ldapDir)
    generate_config('sender-login-maps.cf.j2', ldapDir)

    subprocess.run(['postmap', configDir + 'postscreen_access'])
    subprocess.run(['postmap', configDir + 'helo_access'])
    subprocess.run(['postmap', configDir + 'without_ptr'])

    logger.info('Setup completed, starting application...')
    os.execv('/usr/sbin/postfix', ['postfix', '-c', configDir, 'start-fg'])
