{{- $openldapYamlSecretName := printf "%s-openldap-yaml" (include "tachydromos.fullname" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tachydromos.fullname" . }}-postfix
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postfix.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tachydromos-postfix
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/postfix/configmap-postfix.yaml") . | sha256sum }}
        checksum/configmap-templates: {{ include (print .Template.BasePath "/postfix/configmap-postfix-templates.yaml") . | sha256sum }}
        checksum/configmap-entrypoint: {{ include (print .Template.BasePath "/postfix/configmap-postfix-entrypoint.yaml") . | sha256sum }}
        checksum/configmap-openldap: {{ include (print .Template.BasePath "/openldap/configmap-openldap.yaml") . | sha256sum }}
        checksum/secret-openldap: {{ include (print .Template.BasePath "/openldap/secret-openldap.yaml") . | sha256sum }}
        {{- with .Values.postfix.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: tachydromos-postfix
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.postfix.image.tag | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tachydromos.fullname" . }}
      securityContext:
        {{- toYaml .Values.postfix.podSecurityContext | nindent 8 }}
      containers:
        - name: postfix
          image: "{{ .Values.postfix.image.repository }}:{{ .Values.postfix.image.tag }}"
          imagePullPolicy: {{ .Values.postfix.image.pullPolicy }}
          command:
            - /entrypoint.py
          ports:
            - name: smtp
              containerPort: {{ ternary 26 25 .Values.postfix.enableProxyProtocol }}
              protocol: TCP
            - name: submission
              containerPort: 587
              protocol: TCP
          resources:
            {{- toYaml .Values.postfix.resources | nindent 12 }}
          volumeMounts:
            - name: templates
              mountPath: /mnt/templates
            - name: config
              mountPath: /mnt/config
              subPath: config
            - name: ldap-config
              mountPath: /mnt/ldap-config
              subPath: config
            - name: ldap-secret
              mountPath: /mnt/ldap-secrets
              subPath: secrets
            - name: entrypoint
              mountPath: /entrypoint.py
              subPath: entrypoint.py
            - name: certs
              mountPath: /tls
              readOnly: true
      volumes:
        - name: templates
          configMap:
            name: {{ include "tachydromos.fullname" . }}-postfix-templates
        - name: config
          configMap:
            name: {{ include "tachydromos.fullname" . }}-postfix-yaml
        - name: ldap-config
          configMap:
            name: {{ include "tachydromos.fullname" . }}-openldap-yaml
        - name: ldap-secret
          secret:
            secretName: {{ .Values.ldap.existingSecret | default $openldapYamlSecretName }}
            defaultMode: 0400
        - name: entrypoint
          configMap:
            name: {{ include "tachydromos.fullname" . }}-postfix-entrypoint
            defaultMode: 0755
        - name: certs
          secret:
            secretName: {{ .Values.sogo.ingress.secretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
