apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-postfix
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  accounts.cf: |
    server_host = tachydromos-openldap
    server_port = 1389
    bind        = yes
    bind_dn     = $LDAP_BINDDN
    bind_pw     = $LDAP_BINDDN_PASSWORD
    search_base = ou=users,${LDAP_ROOT}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = (&(objectClass=mailAccount)(mailActive=TRUE)(mail=%s))
    result_attribute = mail
  aliases.cf: |
    server_host = tachydromos-openldap
    server_port = 1389
    bind        = yes
    bind_dn     = $LDAP_BINDDN
    bind_pw     = $LDAP_BINDDN_PASSWORD
    search_base = ou=users,${LDAP_ROOT}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = (&(objectClass=mailAccount)(mailActive=TRUE)(mailAlias=%s))
    result_attribute = mail
  domains.cf: |
    server_host = tachydromos-openldap
    server_port = 1389
    bind        = yes
    bind_dn     = $LDAP_BINDDN
    bind_pw     = $LDAP_BINDDN_PASSWORD
    search_base = ou=domains,${LDAP_ROOT}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = (&(objectClass=organizationalUnit)(ou=%s))
    result_attribute = ou
  recipient-access.cf: |
    server_host = tachydromos-openldap
    server_port = 1389
    bind        = yes
    bind_dn     = $LDAP_BINDDN
    bind_pw     = $LDAP_BINDDN_PASSWORD
    search_base = ou=users,${LDAP_ROOT}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = (&(objectClass=mailAccount)(mail=%s)(|(mailSendOnly=TRUE)(mailActive=FALSE)))
    result_attribute = mail
    result_format    = REJECT
  sender-login-maps.cf: |
    server_host = tachydromos-openldap
    server_port = 1389
    bind        = yes
    bind_dn     = $LDAP_BINDDN
    bind_pw     = $LDAP_BINDDN_PASSWORD
    search_base = ou=users,${LDAP_ROOT}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = (&(objectClass=mailAccount)(mailActive=TRUE)(|(mail=%s)(mailAlias=%s)(mailSuperUser=TRUE)))
    result_attribute = mail
