{{- $defaultHost := printf "%s-openldap" (include "tachydromos.fullname" .) -}}
{{- if .Values.ldap.openldap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap-env
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  LDAP_ROOT: {{ .Values.ldap.root }}
  LDAP_ADMIN_USERNAME: {{ .Values.ldap.adminUsername }}
  LDAP_ADMIN_ATTRIBUTE: {{ .Values.ldap.adminAttribute }}
  LDAP_BINDDN_USERNAME: {{ .Values.ldap.binddnUsername }}
  LDAP_BINDDN_ATTRIBUTE: {{ .Values.ldap.binddnAttribute }}
  LDAP_SKIP_DEFAULT_TREE: "yes"
  LDAP_CUSTOM_SCHEMA_DIR: /bootstrap/schemas
{{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  config: |
    ldapHost: {{ ternary $defaultHost .Values.ldap.host .Values.ldap.openldap.enabled }}
    ldapPort: {{ ternary 389 .Values.ldap.port .Values.ldap.openldap.enabled }}
    ldapRoot: {{ .Values.ldap.root }}
    ldapUserSearchBase: {{ ternary "users" .Values.ldap.userSearchBase .Values.ldap.openldap.enabled }}
    ldapUserAttribute: {{ ternary "ou" .Values.ldap.userAttribute .Values.ldap.openldap.enabled }}
    ldapDomainSearchBase: {{ ternary "domains" .Values.ldap.domainSearchBase .Values.ldap.openldap.enabled }}
    ldapDomainAttribute: {{ ternary "ou" .Values.ldap.domainAttribute .Values.ldap.openldap.enabled }}
    ldapBinddnUsername: {{ .Values.ldap.binddnUsername }}
    ldapBinddnAttribute: {{ .Values.ldap.binddnAttribute }}
