{{- $defaultHost := printf "%s-openldap" (include "tachydromos.fullname" .) -}}
{{- if .Values.ldap.embedded.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap-env
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  LDAP_ROOT: {{ .Values.ldap.rootDn }}
  LDAP_ADMIN_USERNAME: {{ .Values.ldap.adminUsername }}
  LDAP_ADMIN_ATTRIBUTE_TYPE: {{ .Values.ldap.adminAttributeType }}
  LDAP_BINDDN_USERNAME: {{ .Values.ldap.binddnUsername }}
  LDAP_BINDDN_ATTRIBUTE_TYPE: {{ .Values.ldap.binddnAttributeType }}
  LDAP_SKIP_DEFAULT_TREE: "yes"
  LDAP_CUSTOM_SCHEMA_DIR: /bootstrap/schemas
{{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  config: |
    ldapHost: {{ ternary $defaultHost .Values.ldap.host .Values.ldap.embedded.enabled }}
    ldapPort: {{ ternary 389 .Values.ldap.port .Values.ldap.embedded.enabled }}
    ldapRootDn: {{ .Values.ldap.rootDn }}
    ldapUserSearchBase: {{ ternary "ou=users" .Values.ldap.userSearchBase .Values.ldap.embedded.enabled }}
    ldapDomainSearchBase: {{ ternary "ou=domains" .Values.ldap.domainSearchBase .Values.ldap.embedded.enabled }}
    ldapBinddnUsername: {{ .Values.ldap.binddnUsername }}
    ldapBinddnAttributeType: {{ .Values.ldap.binddnAttributeType }}
