{{- if .Values.openldap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap-env
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  LDAP_ROOT: {{ .Values.ldap.root }}
  LDAP_ADMIN_USERNAME: {{ .Values.ldap.adminUsername }}
  LDAP_ADMIN_ATTRIBUTE: {{ .Values.ldap.adminAttribute }}
  LDAP_BINDDN_USERNAME: {{ .Values.ldap.binddnUsername }}
  LDAP_BINDDN_ATTRIBUTE: {{ .Values.ldap.binddnAttribute }}
  LDAP_SKIP_DEFAULT_TREE: "yes"
  LDAP_CUSTOM_SCHEMA_DIR: /bootstrap/schemas
{{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  config: |
    ldapHost: {{ .Values.ldap.host }}
    ldapPort: {{ .Values.ldap.port}}
    ldapRoot: {{ .Values.ldap.root }}
    ldapUserSearchBase: {{ .Values.ldap.userSearchBase }}
    ldapUserAttribute: {{ .Values.ldap.userAttribute }}
    ldapDomainSearchBase: {{ .Values.ldap.domainSearchBase }}
    ldapDomainAttribute: {{ .Values.ldap.domainAttribute }}
    ldapBinddnUsername: {{ .Values.ldap.binddnUsername }}
    ldapBinddnAttribute: {{ .Values.ldap.binddnAttribute }}
