{{- if .Values.ldap.openldap.enabled }}
{{- $openldapEnvSecretName := printf "%s-openldap-env" (include "tachydromos.fullname" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ldap.openldap.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tachydromos-openldap
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/openldap/configmap-openldap.yaml") . | sha256sum }}
        checksum/configmap-bootstrap: {{ include (print .Template.BasePath "/openldap/configmap-openldap-bootstrap.yaml") . | sha256sum }}
        checksum/configmap-schemas: {{ include (print .Template.BasePath "/openldap/configmap-openldap-schemas.yaml") . | sha256sum }}
        checksum/secret: {{ include (print .Template.BasePath "/openldap/secret-openldap.yaml") . | sha256sum }}
        {{- with .Values.postfix.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: tachydromos-openldap
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.ldap.openldap.image.tag | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tachydromos.fullname" . }}
      securityContext:
        {{- toYaml .Values.ldap.openldap.podSecurityContext | nindent 8 }}
      containers:
        - name: openldap
          image: "{{ .Values.ldap.openldap.image.repository }}:{{ .Values.ldap.openldap.image.tag }}"
          imagePullPolicy: {{ .Values.ldap.openldap.image.pullPolicy }}
          ports:
            - name: ldap
              containerPort: 1389
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "tachydromos.fullname" . }}-openldap-env
            - secretRef:
                name: {{ .Values.ldap.existingSecret | default $openldapEnvSecretName }}
          resources:
            {{- toYaml .Values.ldap.openldap.resources | nindent 12 }}
          volumeMounts:
            - name: schemas
              mountPath: /bootstrap/schemas
            - name: bootstrap
              mountPath: /docker-entrypoint-initdb.d
            {{- if .Values.ldap.openldap.persistence.enabled }}
            - name: data
              mountPath: /bitnami/openldap
            {{- end }}
      volumes:
        - name: schemas
          configMap:
            name: {{ include "tachydromos.fullname" . }}-openldap-schemas
        - name: bootstrap
          configMap:
            name: {{ include "tachydromos.fullname" . }}-openldap-bootstrap
        {{- if .Values.ldap.openldap.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "tachydromos.fullname" . }}-openldap
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
