{{- $adminPass := randAlphaNum 20 | nospace -}}
{{- $binddnPass := randAlphaNum 20 | nospace -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: {{ $adminPass }}
  LDAP_BINDDN_PASSWORD: {{ $binddnPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap-shared
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets: |
    ldapAdminPassword: {{ $adminPass }}
    ldapBinddnPassword: {{ $binddnPass }}
