{{- if not (.Values.ldap.existingSecret) }}
{{- $secretName := printf "%s-openldap-env" (include "tachydromos.fullname" .) -}}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- $adminPassword := (get $secretData "LDAP_ADMIN_PASSWORD") | b64dec | default (randAlphaNum 20 | nospace) -}}
{{- $binddnPassword := (get $secretData "LDAP_BINDDN_PASSWORD") | b64dec | default (randAlphaNum 20 | nospace) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap-env
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: {{ $adminPassword }}
  LDAP_BINDDN_PASSWORD: {{ $binddnPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets: |
    ldapBinddnPassword: {{ $binddnPassword }}
{{- end }}
