apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: {{ randAlphaNum 20 | nospace }}
  LDAP_BINDDN_PASSWORD: {{ randAlphaNum 20 | nospace }}

