{{- if .Values.ldap.openldap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tachydromos.fullname" . }}-openldap
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ldap.openldap.service.type }}
  selector:
    app.kubernetes.io/name: tachydromos-openldap
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: ldap
      port: 1389
      targetPort: ldap
      protocol: TCP
      {{- if and (eq .Values.ldap.openldap.service.type "NodePort") (not (empty .Values.ldap.openldap.service.nodePorts.ldap)) }}
      nodePort: {{ .Values.ldap.openldap.service.nodePorts.ldap }}
      {{- end }}
{{- end }}
