{{- $secretName := printf "%s-rspamd-env" (include "tachydromos.fullname" .) -}}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- $rspamdPassword := (get $secretData "RSPAMD_PASSWORD") | b64dec | default (randAlphaNum 20 | nospace) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-rspamd-env
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  RSPAMD_PASSWORD: "{{ $rspamdPassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-rspamd-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets: |
    rspamdPassword: {{ $rspamdPassword }}
