apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tachydromos.fullname" . }}-postfix
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postfix.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tachydromos-postfix
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/configmap-postfix.yaml") . | sha256sum }}
        checksum/secret: {{ include (print .Template.BasePath "/secret-postfix.yaml") . | sha256sum }}
        {{- with .Values.postfix.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: tachydromos-postfix
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.postfix.image.tag | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tachydromos.fullname" . }}
      securityContext:
        {{- toYaml .Values.postfix.podSecurityContext | nindent 8 }}
      initContainers:
        - name: postfix-init
          image: "{{ .Values.postfix.image.repository }}:{{ .Values.postfix.image.tag }}"
          imagePullPolicy: {{ .Values.postfix.image.pullPolicy }}
          resources:
            {{- toYaml .Values.postfix.resources | nindent 12 }}
          command:
            - sh
            - -c
            - |
              mkdir /mnt/configvolume/ldap
              cp -LR /etc/postfix/* /mnt/configvolume/
              cp -LR /mnt/configmap/* /mnt/configvolume/
              cp -LR /mnt/secret/* /mnt/configvolume/ldap/
              postmap /mnt/configvolume/helo_access
              postmap /mnt/configvolume/postscreen_access
              postmap /mnt/configvolume/without_ptr
          volumeMounts:
            - name: configmap
              mountPath: /mnt/configmap
            - name: secret
              mountPath: /mnt/secret
            - name: configvolume
              mountPath: /mnt/configvolume
      containers:
        - name: postfix
          image: "{{ .Values.postfix.image.repository }}:{{ .Values.postfix.image.tag }}"
          imagePullPolicy: {{ .Values.postfix.image.pullPolicy }}
          ports:
            - name: smtp
              containerPort: {{ ternary 26 25 .Values.postfix.enableProxyProtocol }}
              protocol: TCP
            - name: submission
              containerPort: 587
              protocol: TCP
          resources:
            {{- toYaml .Values.postfix.resources | nindent 12 }}
          volumeMounts:
            - name: configvolume
              mountPath: /etc/postfix
              readOnly: true
            - name: certs
              mountPath: /tls
              readOnly: true
      volumes:
        - name: configmap
          configMap:
            name: {{ include "tachydromos.fullname" . }}-postfix
        - name: secret
          secret:
            secretName: {{ include "tachydromos.fullname" . }}-postfix
        - name: configvolume
          emptyDir: {}
        - name: certs
          secret:
            secretName: {{ .Values.ingress.secretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
