apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-postfix
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  accounts.cf: |
    server_host = {{ ternary .Values.postfix.ldap.host "openldap" .Values.postfix.ldap.external }}
    server_port = {{ ternary .Values.postfix.ldap.port 389 .Values.postfix.ldap.external }}
    bind        = yes
    bind_dn     = {{ ternary .Values.postfix.ldap.bindDn "cn=reader,dc=tachydromos,dc=org" .Values.postfix.ldap.external }}
    bind_pw     = {{ ternary .Values.postfix.ldap.bindPassword "openldap" .Values.postfix.ldap.external }} # TODO autoinclude OpenLDAP PW
    search_base = {{ ternary .Values.postfix.ldap.searchBase "ou=users,dc=tachydromos,dc=org" .Values.postfix.ldap.external }}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = {{ ternary .Values.postfix.ldap.accountsFilter "(&(objectClass=mailAccount)(mailActive=TRUE)(mail=%s))" (and (.Values.postfix.ldap.external) (.Values.postfix.ldap.accountsFilter)) }}
    result_attribute = {{ ternary .Values.postfix.ldap.accountsAttribute "mail" (and (.Values.postfix.ldap.external) (.Values.postfix.ldap.accountsAttribute)) }}
  aliases.cf: |
    server_host = {{ ternary .Values.postfix.ldap.host "openldap" .Values.postfix.ldap.external }}
    server_port = {{ ternary .Values.postfix.ldap.port 389 .Values.postfix.ldap.external }}
    bind        = yes
    bind_dn     = {{ ternary .Values.postfix.ldap.bindDn "cn=reader,dc=tachydromos,dc=org" .Values.postfix.ldap.external }}
    bind_pw     = {{ ternary .Values.postfix.ldap.bindPassword "openldap" .Values.postfix.ldap.external }} # TODO autoinclude OpenLDAP PW
    search_base = {{ ternary .Values.postfix.ldap.searchBase "ou=users,dc=tachydromos,dc=org" .Values.postfix.ldap.external }}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = {{ ternary .Values.postfix.ldap.aliasesFilter "(&(objectClass=mailAccount)(mailActive=TRUE)(mailAlias=%s))" (and (.Values.postfix.ldap.external) (.Values.postfix.ldap.aliasesFilter)) }}
    result_attribute = {{ ternary .Values.postfix.ldap.aliasesAttribute "mail" (and (.Values.postfix.ldap.external) (.Values.postfix.ldap.aliasesAttribute)) }}
  domains.cf: |
    server_host = {{ ternary .Values.postfix.ldap.host "openldap" .Values.postfix.ldap.external }}
    server_port = {{ ternary .Values.postfix.ldap.port 389 .Values.postfix.ldap.external }}
    bind        = yes
    bind_dn     = {{ ternary .Values.postfix.ldap.bindDn "cn=reader,dc=tachydromos,dc=org" .Values.postfix.ldap.external }}
    bind_pw     = {{ ternary .Values.postfix.ldap.bindPassword "openldap" .Values.postfix.ldap.external }} # TODO autoinclude OpenLDAP PW
    search_base = {{ ternary .Values.postfix.ldap.searchBase "ou=users,dc=tachydromos,dc=org" .Values.postfix.ldap.external }}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = {{ ternary .Values.postfix.ldap.domainFilter "(&(objectClass=organizationalUnit)(ou=%s))" (and (.Values.postfix.ldap.external) (.Values.postfix.ldap.domainFilter)) }}
    result_attribute = {{ ternary .Values.postfix.ldap.domainAttribute "ou" (and (.Values.postfix.ldap.external) (.Values.postfix.ldap.domainAttribute)) }}
  recipient-access.cf: |
    server_host = {{ ternary .Values.postfix.ldap.host "openldap" .Values.postfix.ldap.external }}
    server_port = {{ ternary .Values.postfix.ldap.port 389 .Values.postfix.ldap.external }}
    bind        = yes
    bind_dn     = {{ ternary .Values.postfix.ldap.bindDn "cn=reader,dc=tachydromos,dc=org" .Values.postfix.ldap.external }}
    bind_pw     = {{ ternary .Values.postfix.ldap.bindPassword "openldap" .Values.postfix.ldap.external }} # TODO autoinclude OpenLDAP PW
    search_base = {{ ternary .Values.postfix.ldap.searchBase "ou=users,dc=tachydromos,dc=org" .Values.postfix.ldap.external }}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = {{ ternary .Values.postfix.ldap.recipientAccessFilter "(&(objectClass=mailAccount)(mail=%s)(|(mailSendOnly=TRUE)(mailActive=FALSE)))" (and (.Values.postfix.ldap.external) (.Values.postfix.ldap.recipientAccessFilter)) }}
    result_attribute = {{ ternary .Values.postfix.ldap.recipientAccessAttribute "mail" (and (.Values.postfix.ldap.external) (.Values.postfix.ldap.recipientAccessAttribute)) }}
    result_format    = REJECT
  sender-login-maps.cf: |
    server_host = {{ ternary .Values.postfix.ldap.host "openldap" .Values.postfix.ldap.external }}
    server_port = {{ ternary .Values.postfix.ldap.port 389 .Values.postfix.ldap.external }}
    bind        = yes
    bind_dn     = {{ ternary .Values.postfix.ldap.bindDn "cn=reader,dc=tachydromos,dc=org" .Values.postfix.ldap.external }}
    bind_pw     = {{ ternary .Values.postfix.ldap.bindPassword "openldap" .Values.postfix.ldap.external }} # TODO autoinclude OpenLDAP PW
    search_base = {{ ternary .Values.postfix.ldap.searchBase "ou=users,dc=tachydromos,dc=org" .Values.postfix.ldap.external }}
    scope       = sub
    dereference = 0
    version     = 3
    query_filter     = {{ ternary .Values.postfix.ldap.senderAccessFilter "(&(objectClass=mailAccount)(mailActive=TRUE)(|(mail=%s)(mailAlias=%s)(mailSuperUser=TRUE)))" (and (.Values.postfix.ldap.external) (.Values.postfix.ldap.senderAccessFilter)) }}
    result_attribute = {{ ternary .Values.postfix.ldap.senderAccessAttribute "mail" (and (.Values.postfix.ldap.external) (.Values.postfix.ldap.senderAccessAttribute)) }}


