nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

hostname: testmail.gregorius.tech

ldap:
  embedded:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/openldap
      tag: 2.6.6
      pullPolicy: IfNotPresent
    podAnnotations: {}
    podSecurityContext: {}
    resources:
      requests:
        memory: 32Mi
        cpu: 50m
      limits:
        memory: 64Mi
        cpu: 100m
    service:
      type: NodePort
      nodePorts:
        ldap: ""
    persistence:
      enabled: false
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      annotations:
        helm.sh/resource-policy: keep
  host: tachydromos-openldap
  port: 389
  rootDn: dc=tachydromos,dc=org
  userSearchBase: ou=users
  domainSearchBase: domains
  adminUsername: admin
  adminAttributeType: cn
  binddnUsername: reader
  binddnAttributeType: cn
  existingSecret: ~

database:
  embedded:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 16.0.0
      pullPolicy: IfNotPresent
    podAnnotations: {}
    podSecurityContext: {}
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 512Mi
        cpu: 1000m
    service:
      type: NodePort
      nodePorts:
        psql: ""
    persistence:
      enabled: false
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      annotations:
        helm.sh/resource-policy: keep
  host: tachydromos-postgresql
  port: 5432
  database: sogo
  username: pgsogo
  existingSecret: ~

postfix:
  image:
    registry: docker.io
    repository: olivergregorius/postfix
    tag: 3.8.2-alpha
    pullPolicy: Always
  replicas: 1
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: 32Mi
      cpu: 50m
    limits:
      memory: 64Mi
      cpu: 100m
  service:
    type: NodePort
    nodePorts:
      smtp: ""
      submission: ""
  enableProxyProtocol: true
  heloWhitelist: ""
  postscreenWhitelist: ""
  ptrWhitelist: ""

dovecot:
  image:
    registry: docker.io
    repository: olivergregorius/dovecot
    tag: 2.3.20-alpha
    pullPolicy: Always
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: 32Mi
      cpu: 50m
    limits:
      memory: 64Mi
      cpu: 100m
  persistence:
    enabled: false
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations:
      helm.sh/resource-policy: keep
  postmasterEmail: postmaster@example.org
  superuserUsername: sysmail@example.org
  existingSecret: ~

rspamd:
  image:
    registry: docker.io
    repository: olivergregorius/rspamd
    tag: 3.6.0-alpha
    pullPolicy: Always
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 1000m
  service:
    type: ClusterIP
    nodePorts:
      milter: ""
      webinterface: ""
  persistence:
    enabled: false
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations:
      helm.sh/resource-policy: keep
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: zerossl-production
    hostname: rspamd.testmail.gregorius.tech
    paths:
      - path: /
        serviceName: rspamd
        servicePort: 11334
    secretName: tachydromos-certificate-rspamd
  dkimSelector: "2023"
  existingSecret: ~
  sidecars:
    redis:
      image:
        registry: docker.io
        repository: redis
        tag: 7.2.1
        pullPolicy: IfNotPresent
      resources:
        requests:
          memory: 32Mi
          cpu: 50m
        limits:
          memory: 64Mi
          cpu: 100m

sogo:
  image:
    repository: docker.io/olivergregorius/sogo
    tag: 5.9.0-alpha
    pullPolicy: Always
  replicas: 1
  podAnnotations: {}
  podSecurityContext:
    fsGroup: 999
    fsGroupChangePolicy: OnRootMismatch
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1.5Gi
      cpu: 500m
  service:
    type: ClusterIP
    nodePorts:
      http: ""
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: zerossl-production
      nginx.ingress.kubernetes.io/app-root: /SOGo
      nginx.ingress.kubernetes.io/proxy-body-size: 16M
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "64"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "512k"
    hostname: ""
    paths:
      - path: /
        serviceName: sogo
        servicePort: 8080
    secretName: tachydromos-certificate
  nginx:
    image:
      repository: docker.io/nginx
      tag: 1.25.2
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 32Mi
        cpu: 50m
      limits:
        memory: 64Mi
        cpu: 100m
  memcached:
    image:
      repository: docker.io/memcached
      tag: 1.6.21
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 32Mi
        cpu: 50m
      limits:
        memory: 64Mi
        cpu: 100m

nodeSelector: {}
affinity: {}
tolerations: {}
