nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

hostname: testmail.gregorius.tech

openldap:
  image:
    repository: docker.io/bitnami/openldap
    tag: 2.6.4
    pullPolicy: IfNotPresent
  replicas: 1
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: 32Mi
      cpu: 50m
    limits:
      memory: 64Mi
      cpu: 100m
  service:
    type: NodePort
    nodePorts:
      ldap: ""
  persistence:
    enabled: false
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations:
      helm.sh/resource-policy: keep

postfix:
  image:
    repository: docker.io/olivergregorius/postfix
    tag: 3.8.1-alpha
    pullPolicy: Always
  replicas: 1
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: 32Mi
      cpu: 50m
    limits:
      memory: 64Mi
      cpu: 100m
  service:
    type: NodePort
    nodePorts:
      smtp: ""
      submission: ""
  enableProxyProtocol: true
  heloWhitelist: ""
  postscreenWhitelist: ""
  ptrWhitelist: ""

dovecot:
  image:
    repository: docker.io/olivergregorius/dovecot
    tag: 2.3.20-alpha
    pullPolicy: Always
  replicas: 1
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: 32Mi
      cpu: 50m
    limits:
      memory: 64Mi
      cpu: 100m
  postmasterEmail: postmaster@example.org
  superuserUsername: sysmail@example.org

rspamd:
  image:
    repository: docker.io/olivergregorius/rspamd
    tag: 3.5.0-alpha
    pullPolicy: Always
  replicas: 1
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 1000m
  service:
    type: NodePort
    nodePorts:
      milter: ""
      webinterface: ""
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: zerossl-production
    hostname: rspamd.testmail.gregorius.tech
    paths:
      - path: /
        serviceName: rspamd
        servicePort: 11334
    secretName: tachydromos-certificate-rspamd
  dkimSelector: "2023"
  sidecars:
    redis:
      image:
        repository: docker.io/redis
        tag: 7.0.11
        pullPolicy: IfNotPresent
      resources:
        requests:
          memory: 32Mi
          cpu: 50m
        limits:
          memory: 64Mi
          cpu: 100m

postgresql:
  image:
    repository: docker.io/bitnami/postgresql
    tag: 15.3.0
    pullPolicy: IfNotPresent
  replicas: 1
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 512Mi
      cpu: 1000m
  service:
    type: NodePort
    nodePorts:
      psql: ""

sogo:
  image:
    repository: docker.io/olivergregorius/sogo
    tag: 5.7.1-alpha
    pullPolicy: Always
  replicas: 1
  podAnnotations: {}
  podSecurityContext:
    fsGroup: 999
    fsGroupChangePolicy: OnRootMismatch
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1.5Gi
      cpu: 500m
  service:
    type: NodePort
    nodePorts:
      http: ""
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: zerossl-production
      nginx.ingress.kubernetes.io/app-root: /SOGo
      nginx.ingress.kubernetes.io/proxy-body-size: 16M
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "64"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "512k"
    hostname: ""
    paths:
      - path: /
        serviceName: sogo
        servicePort: 8080
    secretName: tachydromos-certificate
  nginx:
    image:
      repository: docker.io/nginx
      tag: 1.25.1
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 32Mi
        cpu: 50m
      limits:
        memory: 64Mi
        cpu: 100m
  memcached:
    image:
      repository: docker.io/memcached
      tag: 1.6.21
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 32Mi
        cpu: 50m
      limits:
        memory: 64Mi
        cpu: 100m

nodeSelector: {}
affinity: {}
tolerations: {}
