{{- $defaultHost := printf "%s-postgresql" (include "tachydromos.fullname" .) -}}
{{- if .Values.database.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-postgresql-env
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  POSTGRESQL_DATABASE: {{ .Values.database.database }}
  POSTGRESQL_USERNAME: {{ .Values.database.username }}
{{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-postgresql-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  config: |
    postgresqlHost: {{ ternary $defaultHost .Values.database.host .Values.database.postgresql.enabled }}
    postgresqlPort: {{ ternary 5432 .Values.database.port .Values.database.postgresql.enabled }}
    postgresqlDatabase: {{ .Values.database.database }}
    postgresqlUsername: {{ .Values.database.username }}
