{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-postgresql-env
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  POSTGRESQL_DATABASE: {{ .Values.database.database }}
  POSTGRESQL_USERNAME: {{ .Values.database.username }}
{{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-postgresql-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  config: |
    postgresqlHost: {{ .Values.database.host }}
    postgresqlPort: {{ .Values.database.port }}
    postgresqlDatabase: {{ .Values.database.database }}
    postgresqlUsername: {{ .Values.database.username }}
