apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-postgresql-env
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  POSTGRESQL_DATABASE: sogo
  POSTGRESQL_USERNAME: pgsogo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-postgresql-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  config: |
    postgresqlDatabase: sogo
    postgresqlUsername: pgsogo
