{{- if and .Values.database.embedded.enabled (not .Values.database.embedded.existingSecret) }}
{{- $secretName := printf "%s-postgresql-env" (include "tachydromos.fullname" .) -}}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- $postgresqlPostgresPassword := (get $secretData "POSTGRESQL_POSTGRES_PASSWORD") | b64dec | default (randAlphaNum 20 | nospace) -}}
{{- $postgresqlPassword := (get $secretData "POSTGRESQL_PASSWORD") | b64dec | default (randAlphaNum 20 | nospace) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-postgresql-env
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRESQL_POSTGRES_PASSWORD: {{ $postgresqlPostgresPassword }}
  POSTGRESQL_PASSWORD: {{ $postgresqlPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-postgresql-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets: |
    postgresqlPassword: {{ $postgresqlPassword }}
{{- end }}
