apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-sogo-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  config: |
    workerCount: {{ .Values.sogo.workerCount }}
    workerMemLimitMb: {{ .Values.sogo.workerMemoryLimitMb }}
