apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-sogo-nginx
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  # /etc/nginx/conf.d/
  sogo.nginx.conf: |
    server
    {
      listen 8080;

      root /usr/lib/GNUstep/SOGo/WebServerResources/;

      ## requirement to create new calendars in Thunderbird ##
      proxy_http_version 1.1;

      location = /
      {
        allow all;
      }

      # For iOS 7
      location = /principals/
      {
        allow all;
      }

      location ^~/SOGo
      {
        proxy_pass http://127.0.0.1:20000;
        proxy_redirect http://127.0.0.1:20000 default;

        # forward user's IP address
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header x-webobjects-server-protocol HTTP/1.0;
        proxy_set_header x-webobjects-remote-host 127.0.0.1;
        proxy_set_header x-webobjects-server-url $scheme://$host;
        proxy_set_header x-webobjects-server-port $server_port;

        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;
        proxy_buffer_size 128k;
        proxy_buffers 64 512k;
        proxy_busy_buffers_size 512k;
        client_max_body_size 16m;
      }

      location /SOGo.woa/WebServerResources/
      {
        alias /usr/lib/GNUstep/SOGo/WebServerResources/;
        allow all;
        expires max;
      }

      location /SOGo/WebServerResources/
      {
        alias /usr/lib/GNUstep/SOGo/WebServerResources/;
        allow all;
        expires max;
      }

      location (^/SOGo/so/ControlPanel/Products/([^/]*)/Resources/(.*)$)
      {
        alias /usr/lib/GNUstep/SOGo/$1.SOGo/Resources/$2;
        expires max;
      }

      location (^/SOGo/so/ControlPanel/Products/[^/]*UI/Resources/.*\.(jpg|png|gif|css|js)$)
      {
        alias /usr/lib/GNUstep/SOGo/$1.SOGo/Resources/$2;
        expires max;
      }

      location ^~ /Microsoft-Server-ActiveSync
      {
        proxy_pass http://127.0.0.1:20000/SOGo/Microsoft-Server-ActiveSync;
        proxy_redirect http://127.0.0.1:20000/SOGo/Microsoft-Server-ActiveSync /;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_connect_timeout 75;
        proxy_send_timeout 3540;
        proxy_read_timeout 3540;
        proxy_buffers 64 512k;
        client_body_buffer_size 512k;
        client_max_body_size 16m;

        access_log /var/log/nginx/activesync.log;
        error_log  /var/log/nginx/activesync-error.log;
        resolver 10.43.0.10;
      }
    }
