apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-sogo-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  config: |
    postgresqlHost: tachydromos-postgresql
    postgresqlPort: 5432
    workerCount: 6
    workerMemLimitMb: 256
