{{- if .Values.sogo.ingress.enabled -}}
{{- $fullname := include "tachydromos.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tachydromos.fullname" . }}-sogo
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
  {{- with .Values.sogo.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Values.sogo.ingress.secretName }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          {{- range .Values.sogo.ingress.paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-{{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
{{- end }}
