apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-dovecot-entrypoint
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  entrypoint.py: |
    #!/usr/bin/python3
    import logging
    import os
    import shutil
    import yaml

    import jinja2 as j2


    class LogFormatter(logging.Formatter):
      blue = '\x1b[34m'
      green = '\x1b[32m'
      yellow = '\x1b[33m'
      red = '\x1b[31m'
      bold_red = '\x1b[31;1m'
      purple = '\x1b[35m'
      reset = '\x1b[0m'
      time = purple + '%(asctime)s '
      message = reset + '==> %(message)s'

      def __init__(self):
        super().__init__()
        self.FORMATS = {
          logging.DEBUG: self.time + self.blue + '%(levelname)s ' + self.message,
          logging.INFO: self.time + self.green + '%(levelname)s ' + self.message,
          logging.WARNING: self.time + self.yellow + '%(levelname)s ' + self.message,
          logging.ERROR: self.time + self.red + '%(levelname)s ' + self.message,
          logging.CRITICAL: self.time + self.bold_red + '%(levelname)s ' + self.message,
        }

      def format(self, record):
        log_fmt = self.FORMATS.get(record.levelno)
        formatter = logging.Formatter(log_fmt)
        return formatter.format(record)

    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)
    loghandler = logging.StreamHandler()
    loghandler.setLevel(logging.DEBUG)
    loghandler.setFormatter(LogFormatter())
    logger.addHandler(loghandler)


    def load_config():
      config = {}
      with open('/mnt/config', 'r') as filestream:
        config.update(yaml.safe_load(filestream))
      with open('/mnt/secrets', 'r') as filestream:
        config.update(yaml.safe_load(filestream))
      with open('/mnt/ldap-config', 'r') as filestream:
        config.update(yaml.safe_load(filestream))
      with open('/mnt/ldap-secrets', 'r') as filestream:
        config.update(yaml.safe_load(filestream))
      with open('/mnt/rspamd-secrets', 'r') as filestream:
        config.update(yaml.safe_load(filestream))
      return config


    def generate_config(template, target_dir, owner='root', group='root', mode=0o644, dirmode=0o755, set_perms=True):
      target = target_dir + template.removesuffix('.j2')
      logger.info(f'Generating config {target}')
      configfile = j2Env.get_template(template).render(config)
      with open(target, 'w') as fileHandler:
        fileHandler.write(configfile)
      if set_perms:
        set_permissions(target, False, owner, group, mode, dirmode)


    def set_permissions(target, recursive, owner='root', group='root', mode=0o644, dirmode=0o755):
      if recursive:
        for dirpath, dirnames, filenames in os.walk(target):
          shutil.chown(dirpath, owner, group)
          os.chmod(dirpath, dirmode)
          for filename in filenames:
            shutil.chown(os.path.join(dirpath, filename), owner, group)
            os.chmod(os.path.join(dirpath, filename), mode)
      else:
        shutil.chown(target, owner, group)
        if os.path.isdir(target):
          os.chmod(target, dirmode)
        else:
          os.chmod(target, mode)


    def j2_finalize(value):
      return value if value is not None else ''


    config = load_config()
    j2Env = j2.Environment(loader=j2.FileSystemLoader('/mnt/templates'), finalize=j2_finalize, keep_trailing_newline=True)


    configDir = '/etc/dovecot/'
    confdDir = configDir + 'conf.d/'

    workDir = '/srv/dovecot/'
    set_permissions(workDir, False, 'vmail', 'vmail', dirmode=0o750)

    sieveDir = workDir + 'sieve/'
    if not os.path.isdir(sieveDir):
      os.mkdir(sieveDir)
      set_permissions(sieveDir, False, 'vmail', 'vmail', dirmode=0o700)

    sieveGlobalDir = sieveDir + 'global/'
    if not os.path.isdir(sieveGlobalDir):
      os.mkdir(sieveGlobalDir)
      set_permissions(sieveGlobalDir, False, 'vmail', 'vmail', dirmode=0o700)

    generate_config('msmtprc.j2', '/etc/')

    generate_config('dovecot.conf.j2', configDir)
    generate_config('dovecot-ldap.conf.j2', configDir)

    generate_config('10-auth.conf.j2', confdDir)
    generate_config('auth-ldap.conf.ext.j2', confdDir)
    generate_config('10-logging.conf.j2', confdDir)
    generate_config('10-mail.conf.j2', confdDir)
    generate_config('10-master.conf.j2', confdDir)
    generate_config('15-lda.conf.j2', confdDir)
    generate_config('15-mailboxes.conf.j2', confdDir)
    generate_config('20-imap.conf.j2', confdDir)
    generate_config('20-lmtp.conf.j2', confdDir)
    generate_config('90-plugin.conf.j2', confdDir)

    generate_config('spam-global.sieve.j2', sieveGlobalDir, 'vmail', 'vmail', 0o600)
    generate_config('learn-ham.sh.j2', sieveGlobalDir, 'vmail', 'vmail', 0o700)
    generate_config('learn-ham.sieve.j2', sieveGlobalDir, 'vmail', 'vmail', 0o600)
    generate_config('learn-spam.sh.j2', sieveGlobalDir, 'vmail', 'vmail', 0o700)
    generate_config('learn-spam.sieve.j2', sieveGlobalDir, 'vmail', 'vmail', 0o600)

    logger.info('Setup completed, starting application...')
    os.execv('/usr/sbin/dovecot', ['dovecot', '-c', configDir + 'dovecot.conf', '-F'])
