apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-dovecot-sieve
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  learn-ham.sh: |
    #!/bin/sh
    curl --silent --data-binary @- http://tachydromos-rspamd:11334/learnham?password=$RSPAMD_PASSWORD
  learn-ham.sieve: |
    require ["vnd.dovecot.pipe", "copy", "imapsieve"];
    pipe :copy "learn-ham.sh";
  learn-spam.sh: |
    #!/bin/sh
    curl --silent --data-binary @- http://tachydromos-rspamd:11334/learnspam?password=$RSPAMD_PASSWORD
  learn-spam.sieve: |
    require ["vnd.dovecot.pipe", "copy", "imapsieve"];
    pipe :copy "learn-spam.sh";
  spam-global.sieve: |
    require "fileinto";

    if header :contains "X-Spam-Flag" "YES" {
        fileinto "Junk";
    }

    if header :is "X-Spam" "Yes" {
        fileinto "Junk";
    }
