apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tachydromos.fullname" . }}-dovecot
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
data:
  config: |
    postmasterEmail: {{ .Values.dovecot.postmasterEmail }}
    superuserUsername: {{ .Values.dovecot.superuserUsername }}
