apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tachydromos.fullname" . }}-dovecot
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dovecot.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tachydromos-dovecot
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/dovecot/configmap-dovecot.yaml") . | sha256sum }}
        checksum/secret: {{ include (print .Template.BasePath "/dovecot/secret-dovecot.yaml") . | sha256sum }}
        checksum/configmap-templates: {{ include (print .Template.BasePath "/dovecot/configmap-dovecot-templates.yaml") . | sha256sum }}
        checksum/configmap-entrypoint: {{ include (print .Template.BasePath "/dovecot/configmap-dovecot-entrypoint.yaml") . | sha256sum }}
        checksum/configmap-openldap: {{ include (print .Template.BasePath "/openldap/configmap-openldap.yaml") . | sha256sum }}
        checksum/secret-openldap: {{ include (print .Template.BasePath "/openldap/secret-openldap.yaml") . | sha256sum }}
        {{- with .Values.dovecot.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: tachydromos-dovecot
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.dovecot.image.tag | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tachydromos.fullname" . }}
      securityContext:
        {{- toYaml .Values.dovecot.podSecurityContext | nindent 8 }}
      containers:
        - name: dovecot
          image: "{{ .Values.dovecot.image.repository }}:{{ .Values.dovecot.image.tag }}"
          imagePullPolicy: {{ .Values.dovecot.image.pullPolicy }}
          command:
            - /entrypoint.py
          ports:
            - name: lmtp
              containerPort: 24
              protocol: TCP
            - name: imap
              containerPort: 143
              protocol: TCP
            - name: sasl
              containerPort: 3659
              protocol: TCP
            - name: sieve
              containerPort: 4190
              protocol: TCP
          resources:
            {{- toYaml .Values.dovecot.resources | nindent 12 }}
          volumeMounts:
            - name: templates
              mountPath: /mnt/templates
            - name: config
              mountPath: /mnt/config
              subPath: config
            - name: secret
              mountPath: /mnt/secrets
              subPath: secrets
            - name: ldap-config
              mountPath: /mnt/ldap-config
              subPath: config
            - name: ldap-secret
              mountPath: /mnt/ldap-secrets
              subPath: secrets
            - name: entrypoint
              mountPath: /entrypoint.py
              subPath: entrypoint.py
            - name: data
              mountPath: /srv/dovecot
      volumes:
        - name: templates
          configMap:
            name: {{ include "tachydromos.fullname" . }}-dovecot-templates
        - name: config
          configMap:
            name: {{ include "tachydromos.fullname" . }}-dovecot-yaml
        - name: secret
          secret:
            secretName: {{ include "tachydromos.fullname" . }}-dovecot-yaml
            defaultMode: 0400
        - name: ldap-config
          configMap:
            name: {{ include "tachydromos.fullname" . }}-openldap-yaml
        - name: ldap-secret
          secret:
            secretName: {{ include "tachydromos.fullname" . }}-openldap-yaml
            defaultMode: 0400
        - name: entrypoint
          configMap:
            name: {{ include "tachydromos.fullname" . }}-dovecot-entrypoint
            defaultMode: 0755
        - name: data
          emptyDir: {} # TODO PVC
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
