{{- if not (.Values.dovecot.existingSecret) }}
{{- $secretName := printf "%s-dovecot-env" (include "tachydromos.fullname" .) -}}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- $superuserPassword := (get $secretData "SUPERUSER_PASSWORD") | b64dec | default (randAlphaNum 20 | nospace) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-dovecot-env
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  SUPERUSER_PASSWORD: "{{ $superuserPassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-dovecot-yaml
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets: |
    superuserPassword: {{ $superuserPassword }}
{{- end }}
