apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachydromos.fullname" . }}-dovecot
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets: |
    superuserPassword: {{ randAlphaNum 20 | nospace }}
    rspamdPassword: {{ randAlphaNum 20 | nospace }}

