apiVersion: v1
kind: Service
metadata:
  name: {{ include "tachydromos.fullname" . }}-dovecot-imap
  labels:
    {{- include "tachydromos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dovecot.service.type }}
  selector:
    app.kubernetes.io/name: tachydromos-dovecot
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: imap
      port: 143
      targetPort: imap
      protocol: TCP
      {{- if and (eq .Values.dovecot.service.type "NodePort") (not (empty .Values.dovecot.service.nodePorts.imap)) }}
      nodePort: {{ .Values.dovecot.service.nodePorts.imap }}
      {{- end }}
